# Generated by Django 5.0 on 2023-12-19 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('idclient', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('direction', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Intervenant',
            fields=[
                ('idInter', models.AutoField(primary_key=True, serialize=False)),
                ('pom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('idintervention', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('type', models.CharField(max_length=100)),
                ('motive', models.TextField()),
                ('etat', models.CharField(max_length=50)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Miniapp.client')),
                ('id_intervenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Miniapp.intervenant')),
            ],
        ),
    ]
